[context.staging.environment]
  VUE_APP_UPLOADER_IMAGE_PRESET="browtricks_tenant_cms_images_dev"
  VUE_APP_UPLOADER_VIDEO_PRESET="browtricks_tenant_cms_videos_dev"
  VUE_APP_UPLOADER_MEDIA_PRESET="browtricks_cms_media_dev"
  VUE_APP_UPLOADER_PDF_PRESET="browtricks_tenant_cms_pdf_dev"
  VUE_APP_API_URL="https://stagingapi.whynot.earth"

[context.master.environment]
  VUE_APP_UPLOADER_IMAGE_PRESET="browtricks_tenant_cms_images"
  VUE_APP_UPLOADER_VIDEO_PRESET="browtricks_tenant_cms_videos"
  VUE_APP_UPLOADER_MEDIA_PRESET="browtricks_cms_media"
  VUE_APP_UPLOADER_PDF_PRESET="browtricks_tenant_cms_pdf"
  VUE_APP_API_URL="https://api.whynot.earth"

[[redirects]]
  from = "/t/*"
  to = "/redirector.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
